# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestInstaGram' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod ‘Firebase/Auth’
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Storage'
  pod 'SDWebImage', '~> 4.0'
  pod 'SnapKit', '~> 4.0.0'
  # Pods for TestInstaGram

end
